POST http://localhost:8080/feeds

{
    "title": "mi curso con node",
    "description": "playground usando node para hacer un curso"
}

###

GET http://localhost:8080/feeds

###

GET http://localhost:8080/search?q=go