services:
  postgres:
    build: "./database"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: mydb
    restart: always
      
  nats:
    image: "nats-streaming:0.17.0"
    restart: always

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.6.2"
    environment:
      - "discovery.type=single-node"

  feed:
    build: '.'
    command: "feed-service"
    depends_on:
      - postgres
      - nats
    ports:
      - "8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: mydb
      NATS_ADDRESS: "nats:4222"

  query:
    build: '.'
    command: "query-service"
    depends_on:
      - postgres
      - nats
      - elasticsearch
    ports:
      - "8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: mydb
      NATS_ADDRESS: "nats:4222"
      ELASTICSEARCH_ADDRESS: "elasticsearch:9200"
  
  pusher:
    build: '.'
    command: "pusher-service"
    depends_on:
      - nats
    ports:
      - "8080"
    environment:
      NATS_ADDRESS: "nats:4222"

  nginx:
    build: "./nginx"
    ports:
      - "8080:80"
    depends_on:
      - feed
      - query
      - pusher